BIN_PATH = ./build/Debug
DATA_PATH = C:/Users/Jan/OneDrive/_Coding/UdemyCExt/12_Advanced/CmdArguments/data

run_0:
	$(BIN_PATH)/outDebug $(DATA_PATH) 0

run_1:
	$(BIN_PATH)/outDebug $(DATA_PATH) 1

run_2:
	$(BIN_PATH)/outDebug $(DATA_PATH) 2
